services:
  pipeline-3d:
    build:
      context: .
      dockerfile: Dockerfile
    image: pipeline-3d:latest
    container_name: pipeline-3d
    environment:
      INPUT_FILE: "teste2_RGB.laz"
      TARGET_VERTICES: "80000"
      POISSON_DEPTH: "10"
      SOR_NEIGHBORS: "20"
      SOR_STD: "1.5"
      SPATIAL_SUBSAMPLE: "0.5"
    volumes:
      - ./input:/pipeline/input:ro
      - ./output:/pipeline/output:rw
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
    restart: "no"